apiVersion: v1
kind: Service
metadata:
  name: service-mysql
  namespace: springboot-kubernetes
  labels:
    app: springboot-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: springboot-mysql
    tier: mysql
  clusterIP: None